[FIX] vcs-clear-retry depends on UpdateError being raised
Without the callwith argument, the CalledProcessError is not intercepted and
replaced by an UpdateError, and in that case the cleaning + retry does not
take place.

```
  File "/mnt/odoo/buildout/src/anybox.recipe.odoo/anybox/recipe/odoo/vcs/git.py", line 351, in get_update
    return self.fetch_remote_sha(revision)
  File "/mnt/odoo/buildout/src/anybox.recipe.odoo/anybox/recipe/odoo/vcs/git.py", line 259, in fetch_remote_sha
    self.log_call(['git', 'checkout', sha])
  File "/mnt/odoo/buildout/src/anybox.recipe.odoo/anybox/recipe/odoo/vcs/git.py", line 147, in log_call
    return callwith(cmd, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', 'a8a54da1ffd1']' returned non-zero exit status 1.
```